export default {
  htmlCode:
    '<!DOCTYPE html>\n<html lang="ja">\n\t<head>\n\t\t<meta charset="UTF-8" />\n\t\t<meta name="viewport" content="width=device-width, initial-scale=1.0" />\n\t\t<title>Document</title>\n\t</head>\n\t<body>\n\t\t<h1 id="app_daimei">Hello PWA!</h1>\n\t\t<p id="app_shoukai">自由に書き換えてみましょう。</p>\n\t</body>\n</html>\n',
  cssCode:
    "#app_daimei {\n\t/* この中で「app_daimei」の見た目を調整 */\n\ttext-align: center; /* 文字等を中央揃え */\n}\n#app_shoukai {\n\t/* この中で「app_shoukai」の見た目を調整 */\n\ttext-align: center; /* 文字等を中央揃え */\n}\n",
  jsCode:
    'const app_shoukai = document.getElementById("app_shoukai"); // 「app_shoukai」の動きを操作するための準備\nconst app_daimei = document.getElementById("app_daimei"); // 「app_daimei」の動きを操作するための準備\n',
  omikujiDiv:
    '\t\t<div id="omikuji_template">\n\t\t\t<div id="omikuji_start">おみくじ</div>\n\t\t\t<div id="daikichi">大吉</div>\n\t\t\t<div id="kichi">吉</div>\n\t\t\t<div id="kyou">凶</div>\n\t\t\t<div id="button_box">\n\t\t\t\t<button id="omikuji_button">おみくじを引く</button>\n\t\t\t</div>\n\t\t</div>\n',
  omikujiCss:
    "#omikuji_start {\n\t/* この中で「omikuji_start」の見た目を調整 */\n\tmargin: 10px auto; /* 上下に10px, 左右に自動の幅をとる */\n\twidth: 200px; /* 横の長さ */\n\theight: 200px; /* 縦の長さ */\n\ttext-align: center; /* 文字等を中央揃え */\n\tline-height: 200px; /* 行間を200pxに設定して上下中央揃え */\n\tbackground-color: lightgray; /* 背景の色 */\n}\n#daikichi {\n\t/* この中で「daikichi」の見た目を調整 */\n\tmargin: 10px auto; /* 上下に10px, 左右に自動の幅をとる */\n\twidth: 200px; /* 横の長さ */\n\theight: 200px; /* 縦の長さ */\n\ttext-align: center; /* 文字等を中央揃え */\n\tline-height: 200px; /* 行間を200pxに設定して上下中央揃え */\n\tfont-weight: bold; /* 文字を太字にする */\n\tfont-size: xx-large; /* 文字を大きくする */\n\tbackground-color: lightpink; /* 背景の色 */\n}\n#kichi {\n\t/* この中で「kichi」の見た目を調整 */\n\tmargin: 10px auto; /* 上下に10px, 左右に自動の幅をとる */\n\twidth: 200px; /* 横の長さ */\n\theight: 200px; /* 縦の長さ */\n\ttext-align: center; /* 文字等を中央揃え */\n\tline-height: 200px; /* 行間を200pxに設定して上下中央揃え */\n\tfont-weight: bold; /* 文字を太字にする */\n\tfont-size: xx-large; /* 文字を大きくする */\n\tbackground-color: lightgreen; /* 背景の色 */\n}\n#kyou {\n\t/* この中で「kyou」の見た目を調整 */\n\tmargin: 10px auto; /* 上下に10px, 左右に自動の幅をとる */\n\twidth: 200px; /* 横の長さ */\n\theight: 200px; /* 縦の長さ */\n\ttext-align: center; /* 文字等を中央揃え */\n\tline-height: 200px; /* 行間を200pxに設定して上下中央揃え */\n\tfont-weight: bold; /* 文字を太字にする */\n\tfont-size: xx-large; /* 文字を大きくする */\n\tbackground-color: lightblue; /* 背景の色 */\n}\n#button_box {\n\ttext-align: center; /* 文字等を中央揃え */\n}\n",
  omikujiJs:
    'const omikuji_button = document.getElementById("omikuji_button"); // 「omikuji_button」の動きを操作するための準備\nconst omikuji_start = document.getElementById("omikuji_start"); // 「omikuji_start」の動きを操作するための準備\nconst daikichi = document.getElementById("daikichi"); // 「daikichi」の動きを操作するための準備\nconst kichi = document.getElementById("kichi"); // 「kichi」の動きを操作するための準備\nconst kyou = document.getElementById("kyou"); // 「kyou」の動きを操作するための準備\ndaikichi.style.display = "none"; // 「daikichi」を隠す\nkichi.style.display = "none"; // 「kichi」を隠す\nkyou.style.display = "none"; // 「kyou」を隠す\nomikuji_button.onclick = () => {\n\t// 「omikuji_button」がクリックされたときの動作\n\tconst r = Math.random(); // 0以上1未満の乱数（ランダムな数）\n\tif (r < 0.3) {\n\t// rが0.3より小さいときの動作\n\tomikuji_start.style.display = "none"; // 「omikuji_start」を隠す\n\tdaikichi.style.display = "block"; // 「daikichi」を表示する\n\tsetTimeout(() => {\n\t// (下の数字÷1000)秒待ってから以下に書いた操作を実行する\n\tdaikichi.style.display = "none"; // 「daikichi」を隠す\n\tomikuji_start.style.display = "block"; // 「omikuji_start」を表示する\n\t}, 1000);\n\t} else if (r < 0.7) {\n\t// rが0.3以上で、0.7より小さいときの動作\n\tomikuji_start.style.display = "none"; // 「omikuji_start」を隠す\n\tkichi.style.display = "block"; // 「kichi」を表示する\n\tsetTimeout(() => {\n\t// (下の数字÷1000)秒待ってから以下に書いた操作を実行する\n\tkichi.style.display = "none"; // 「kichi」を隠す\n\tomikuji_start.style.display = "block"; // 「omikuji_start」を表示する\n\t}, 1000);\n\t} else {\n\t// その他（rが0.7以上）のときの動作\n\tomikuji_start.style.display = "none"; // 「omikuji_start」を隠す\n\tkyou.style.display = "block"; // 「kyou」を表示する\n\tsetTimeout(() => {\n\t// (下の数字÷1000)秒待ってから以下に書いた操作を実行する\n\tkyou.style.display = "none"; // 「kyou」を隠す\n\tomikuji_start.style.display = "block"; // 「omikuji_start」を表示する\n\t}, 1000);\n\t}\n};\n',
  bmiDiv:
    '  <div>\r\n    <h1>BMI\u8a08\u7b97\u30a2\u30d7\u30ea</h1>\r\n    <p>\u300cBMI=\u4f53\u91cd(kg)\u00f7\u8eab\u9577(m)^2\u300d</p>\r\n\r\n    <p><input id="height" type="text" /> cm</p>\r\n    <p><input id="weight" type="text" /> kg</p>\r\n    <div id="box">\r\n      <button id="bmibutton">\u8a08\u7b97\u3059\u308b\uff01</button>\r\n    </div>\r\n    <p>BMI\u306f\u2026\u2026</p>\r\n    <div id="answer">\uff1f\uff1f</div>\r\n  </div>\r\n',
  bmiCss:
    "h1 {\r\n  text-align: center;\r\n}\r\n\r\np {\r\n  text-align: center;\r\n}\r\n\r\n#box {\r\n  /* \u3053\u306e\u4e2d\u3067\u300cbox\u300d\u306e\u898b\u305f\u76ee\u3092\u8abf\u6574 */\r\n  text-align: center; /* \u6587\u5b57\u7b49\u3092\u4e2d\u592e\u63c3\u3048 */\r\n}\r\n#answer {\r\n  /* \u3053\u306e\u4e2d\u3067\u300canswer\u300d\u306e\u898b\u305f\u76ee\u3092\u8abf\u6574 */\r\n  text-align: center; /* \u6587\u5b57\u7b49\u3092\u4e2d\u592e\u63c3\u3048 */\r\n}\r\n",
  bmiJs:
    'const answer = document.getElementById("answer");\r\nconst height = document.getElementById("height");\r\nconst weight = document.getElementById("weight");\r\n\r\nconst bmibutton = document.getElementById("bmibutton");\r\n\r\nbmibutton.onclick = () => {\r\n  // \u300cbutton\u300d\u304c\u30af\u30ea\u30c3\u30af\u3055\u308c\u305f\u3068\u304d\u306e\u52d5\u4f5c\r\n  answer.textContent = weight.value / (height.value / 100) ** 2;\r\n};\r\n',
  todoDiv:
    '    <div id="wrapper">\r\n      <h1>TODO</h1>\r\n      <p>\r\n        \u30bf\u30b9\u30af\u3092\u5165\u529b\u3057\u3066\u300c\u767b\u9332\u300d\u3067\u767b\u9332\u3067\u304d\u307e\u3059\u3002\u30bf\u30b9\u30af\u3092\u30af\u30ea\u30c3\u30af\u3067\u9054\u6210\u6e08\u3001\u53f3\u30af\u30ea\u30c3\u30af\uff08\u30b9\u30de\u30db\u306a\u3089\u9577\u62bc\u3057\uff09\u3067\u524a\u9664\u306b\u306a\u308a\u307e\u3059\u3002\r\n      </p>\r\n      <div>\r\n        <input type="text" id="input" placeholder="\u30bf\u30b9\u30af\u3092\u5165\u529b" />\r\n        <button id="button">\u767b\u9332</button>\r\n      </div>\r\n      <ul id="ul"></ul>\r\n    </div>\r\n',
  todoCss:
    "ul {\r\n  margin: auto;\r\n  width: 150px;\r\n}\r\n#wrapper {\r\n  text-align: center;\r\n}\r\n.line {\r\n  text-decoration: line-through;\r\n}\r\n",
  todoJs:
    'const input = document.getElementById("input");\r\nconst ul = document.getElementById("ul");\r\nconst button = document.getElementById("button");\r\n\r\n// \u30ed\u30fc\u30ab\u30eb\u30b9\u30c8\u30ec\u30fc\u30b8\u306b\u4fdd\u5b58\u3055\u308c\u3066\u3044\u308b\u30c7\u30fc\u30bf\u3092\u30ed\u30fc\u30c9\r\nconst todos = localStorage.getItem("todos");\r\n\r\n// \u30ed\u30fc\u30c9\u3057\u305f\u30c7\u30fc\u30bf\u3092\u66f8\u304d\u8fbc\u3080\r\nul.innerHTML = todos;\r\n\r\nbutton.addEventListener("click", () => {\r\n  if (input.value) {\r\n    // \u3082\u3057\u5165\u529b\u6b04\u304c\u7a7a\u3067\u306a\u304b\u3063\u305f\u3089\r\n    // \u30ea\u30b9\u30c8\u306b\u9805\u76ee\u3092\u8ffd\u52a0\r\n    const li = document.createElement("li");\r\n    li.innerText = input.value;\r\n\r\n    li.addEventListener("contextmenu", (e) => {\r\n      // \u53f3\u30af\u30ea\u30c3\u30af\u3055\u308c\u305f\u3068\u304d\r\n      // \u53f3\u30af\u30ea\u30c3\u30af\u306e\u30e1\u30cb\u30e5\u30fc\u3092\u8868\u793a\u3057\u306a\u3044\r\n      e.preventDefault();\r\n      if (confirm("\u3053\u306e\u30bf\u30b9\u30af\u3092\u524a\u9664\u3057\u307e\u3059")) {\r\n        li.remove();\r\n      }\r\n      // \u30c7\u30fc\u30bf\u3092\u4fdd\u5b58\r\n      const todos = ul.innerHTML;\r\n      localStorage.setItem("todos", todos);\r\n    });\r\n\r\n    li.addEventListener("click", () => {\r\n      // \u5de6\u30af\u30ea\u30c3\u30af\u3055\u308c\u305f\u3068\u304d\r\n      li.classList.toggle("line");\r\n\r\n      // \u30c7\u30fc\u30bf\u3092\u4fdd\u5b58\r\n      const todos = ul.innerHTML;\r\n      localStorage.setItem("todos", todos);\r\n    });\r\n\r\n    ul.appendChild(li);\r\n    // \u5165\u529b\u6b04\u3092\u7a7a\u767d\u306b\u623b\u3059\r\n    input.value = "";\r\n\r\n    // \u30c7\u30fc\u30bf\u3092\u4fdd\u5b58\r\n    const todos = ul.innerHTML;\r\n    localStorage.setItem("todos", todos);\r\n  }\r\n});\r\n',
  serviceWorkerScript: `<script>\r\n      if (\"serviceWorker\" in navigator) {\r\n        navigator.serviceWorker\r\n          .register(\"..\/sw.js\")\r\n          .then(function (registration) {\r\n            console.log(\r\n              \"ServiceWorker registration successful with scope: \",\r\n              registration.scope\r\n            );\r\n          })\r\n          .catch(function (err) {\r\n            console.log(\"ServiceWorker registration failed: \", err);\r\n          });\r\n      }\r\n    <\/script>\n`,
  // divBoxCode:
  //   '<div>テキストを入力</div>\n<style>\n\tmargin: 10px auto;
  //   \n\twidth: 200px;
  //   \n\theight: 200px;
  //   \n\ttext-align: center;
  //   \n\tline-height: 200px;
  //   \n\tfont-size: 36px;
  //   \n\tfont-weight: bold;</style>'
};

// <div id="omikuji-template">\n\t<div class="img-box">\n\t<img\n\t\tid="omikuji-image"\n\t\tsrc="./img/omikuji-box.png"\n\t\talt="おみくじの箱"\n\t/>\n\t</div>\n\t<button id="omikuji-button">おみくじを引く</button>\n\t<script>\n\tconst omikujiButton = document.getElementById("omikuji-button");\n\tconst omikujiImage = document.getElementById("omikuji-image");\n\tomikujiButton.onclick = () => {\n\t\tconst r = Math.random();\n\t\tif (r < 0.3) {\n\t\tomikujiImage.src = "./img/omikuji_daikichi.png";\n\t\tsetTimeout(() => {\n\t\t\tomikujiImage.src = "./img/omikuji-box.png";\n\t\t}, 1000);\n\t\t} else if (r < 0.7) {\n\t\tomikujiImage.src = "./img/omikuji_kichi.png";\n\t\tsetTimeout(() => {\n\t\t\tomikujiImage.src = "./img/omikuji-box.png";\n\t\t}, 1000);\n\t\t} else {\n\t\tomikujiImage.src = "./img/omikuji_kyou.png";\n\t\tsetTimeout(() => {\n\t\t\tomikujiImage.src = "./img/omikuji-box.png";\n\t\t}, 1000);\n\t\t}\n\t};\n\t</script>\n</div>
