version: "3.8"
services:
  postgresdb:
    build:
      context: ./postgresql
      dockerfile: Dockerfile
    container_name: postgresdb
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    image: postgresdb
    ports:
      - "5432:5432"
    user: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data
volumes:
  postgres_volume:
